<a href="https://colab.research.google.com/github/eileen795/MSSP-6070/blob/main/assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')
import glob

# find parsed csv path
import glob
path = glob.glob('/content/drive/MyDrive/**/parsed.csv', recursive=True)
print(path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['/content/drive/MyDrive/MSSP607/Assignments/week_4/Working with Pandas DataFrames/parsed.csv']

In [5]:
import pandas as pd

df = pd.read_csv(path[0])   # path[0] 就是上一步找到的路径
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [6]:
# a. Find the 95th percentile of earthquake magnitude in Japan using magType of 'mb'
japan_mb = df.query("parsed_place == 'Japan' and magType == 'mb'")
p95 = japan_mb['mag'].quantile(0.95)
print(p95)

4.9

In [7]:
#b. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.
indonesia = df.query("parsed_place == 'Indonesia'")
pct = indonesia['tsunami'].mean() * 100
print(f"{pct:.2f}%")

23.13%

In [8]:
#c. Get summary statistics for earthquakes in Nevada
nevada_summary = df.query("parsed_place == 'Nevada'").describe()
print(nevada_summary)

             cdi        dmin       felt         gap         mag   mmi  \
count  15.000000  681.000000  15.000000  681.000000  681.000000  1.00
mean    2.440000    0.166199   2.400000  153.668120    0.500073  2.84
std     0.501142    0.166228   4.626013   68.735302    0.696710   NaN
min     2.000000    0.001000   1.000000   29.140000   -0.500000  2.84
25%     2.000000    0.053000   1.000000   97.380000   -0.100000  2.84
50%     2.200000    0.112000   1.000000  149.140000    0.400000  2.84
75%     2.900000    0.233000   1.000000  199.720000    0.900000  2.84
max     3.300000    1.414000  19.000000  355.910000    2.900000  2.84

              nst         rms         sig          time  tsunami     tz  \
count  681.000000  681.000000  681.000000  6.810000e+02    681.0  681.0
mean    12.618209    0.151986   10.970631  1.538314e+12      0.0 -480.0
std      9.866963    0.084662   19.607150  5.965637e+08      0.0    0.0
min      3.000000    0.000500    0.000000  1.537247e+12      0.0 -480.0
25%      6.000000    0.106900    0.000000  1.537854e+12      0.0 -480.0
50%     10.000000    0.146300    2.000000  1.538280e+12      0.0 -480.0
75%     16.000000    0.187100   12.000000  1.538821e+12      0.0 -480.0
max     61.000000    0.863400  129.000000  1.539461e+12      0.0 -480.0

            updated
count  6.810000e+02
mean   1.538402e+12
std    6.010951e+08
min    1.537307e+12
25%    1.537928e+12
50%    1.538428e+12
75%    1.538878e+12
max    1.539483e+12

In [9]:
#d add a colom
ring_of_fire = [
    'Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica', 'Guatemala',
    '(?<!New )Mexico',
    'Japan', 'Philippines', 'Indonesia', 'New Zealand',
    'Antarctic',
    'Canada', 'Fiji', 'Alaska', 'Washington', 'California',
    'Russia', 'Taiwan', 'Tonga', 'Kermadec Islands'
]

pattern = '|'.join(ring_of_fire)
df['ring_of_fire'] = df['parsed_place'].str.contains(pattern, na=False)

df[['parsed_place', 'ring_of_fire']].head()

  parsed_place  ring_of_fire
0   California          True
1   California          True
2   California          True
3   California          True
4   California          True

In [10]:
#e. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them,
counts = df['ring_of_fire'].value_counts()
print(counts)

ring_of_fire
True     7188
False    2144
Name: count, dtype: int64

In [11]:
# f. Find the tsunami count along the Ring of Fire.
tsunami_rof = df.query('ring_of_fire')['tsunami'].sum()
print(tsunami_rof)

45