<a href="https://colab.research.google.com/github/eileen795/MSSP-6070/blob/main/Modules/week5/excercise_week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import os
import pandas as pd

repo_url = "https://github.com/eileen795/MSSP-6070.git"
repo_name = "MSSP-6070"

# Clone only if the repository has not already been downloaded
if not os.path.exists(f"/content/{repo_name}"):
    !git clone {repo_url}

# Move into the repository folder
os.chdir(f"/content/{repo_name}")
print("Current directory:", os.getcwd())
path = "Modules/week5/"

print("Files in week5 folder:")
print(os.listdir(path))

Current directory: /content/MSSP-6070
Files in week5 folder:
['amzn.csv', 'goog.csv', 'excercise_week5.ipynb', 'aapl.csv', 'nflx.csv', 'faang.csv', 'fb.csv']

In [5]:
# b. Read each file into a dataframe
aapl = pd.read_csv(path + 'aapl.csv')
amzn = pd.read_csv(path + 'amzn.csv')
fb   = pd.read_csv(path + 'fb.csv')
goog = pd.read_csv(path + 'goog.csv')
nflx = pd.read_csv(path + 'nflx.csv')


# c. Add ticker column to each dataframe
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker']   = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'


# d. Append all files into one dataframe
faang = pd.concat(
    [aapl, amzn, fb, goog, nflx],
    ignore_index=True
)


# e. Save the combined dataframe as faang.csv
faang.to_csv(path + 'faang.csv', index=False)


# f. Read faang.csv
faang = pd.read_csv(path + 'faang.csv')

# Convert date column to datetime
faang['date'] = pd.to_datetime(faang['date'])

# Convert volume column to integer
faang['volume'] = faang['volume'].astype(int)

# Sort by date and ticker
faang = faang.sort_values(
    by=['date', 'ticker']
)

faang.head()

           date       open       high        low      close    volume ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
251  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
502  2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
753  2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
1004 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [6]:
# g. Find the seven rows with the highest volume
faang.nlargest(7, 'volume')

          date      open      high       low     close     volume ticker
644 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
555 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
559 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
556 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [7]:
# h. Melt the dataframe
melted = faang.melt(
    id_vars=['date', 'ticker'],
    var_name='variable',
    value_name='value'
)

melted.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000